id: P005414
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:49:11.854166
source_metadata:
  id: bdr:W1CZ874
  title: ལྷ་བསངས་དཔེ་ཐོ
  author: ''
  volumes:
    9f5e4c9f085a4e56b8c20bd7e1e66b1e:
      image_group_id: I1CZ948
      title: ''
      volume_number: 1
      total_pages: 8
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
